# Meta
site_name: Jay's Jenkins X Workshop
site_url: https://joostvdg.github.io/jenkinsx-workshop-demos
# Copyright
copyright: 'Copyright &copy; 2019 Joost van der Griendt'
repo_name: 'joostvdg/jenkinsx-workshop-demos'
repo_url: 'https://github.com/joostvdg/jenkinsx-workshop-demos'

docs_dir: 'docs'

# Pages
nav:
- Home: index.md
- Install: install.md
- Quickstart Demo: go-demo.md

- BuildPack Demo:
  - Import: buildpack/import.md
  - BuildPack: buildpack/index.md

- X-Files Demo:
  - Overview: xfiles/index.md
  - Mulder: xfiles/mulder.md
  - Scully: xfiles/scully.md
  - Integration: xfiles/integration.md

- JX Commands & Tips:
  - Command Overview: tips/commands.md
  - Tips: tips/index.md
  - GitOps: tips/gitops.md
  - Vault: tips/vault.md

- JX Serverless:
  - Intro: serverless/index.md

- Devoxx:
  - Init: devoxx/create-cluster.md
  - Quickstart: devoxx/quickstart.md
  - Environment: devoxx/environment.md

- Preview Env:
  - Introduction: preview/index.md
  - Dependencies: preview/dependencies.md
  - Pipeline: preview/pipeline.md
  - Database: preview/database.md

- Other JX Topics:
  - Custom Domain: other/custom-domain.md
  - Cluster Validation: other/cluster-validation.md
  - Security: other/security.md
  - Issue Trackers: other/issue-trackers.md
  - Alt Git Repo: other/alt-git-repo.md

- Kubernetes:
  - Basics I: k8s/index.md
  - Basics II: k8s/part2.md
  - Basics III: k8s/part3.md
  - Tools: k8s/tools.md
  - Helm: k8s/helm.md
  - Create Cluster: k8s/create-cluster.md

- Kubernetes Advanced:
  - Knative Build: k8s/knative-build.md

# Theme
# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'green'
    accent: 'deep-purple'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'images/logo.svg'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/joostvdg'
    - type: 'twitter'
      link: 'https://twitter.com/joost_vdg'
    - type: 'linkedin'
      link: 'https://linkedin.com/in/joostvdg'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
